[prefs]
author_name =
author_email =
author_primary_affiliation =
project_name =
dataset_version =
dataset_identifier =
data_license =
source_image_origin =
source_image_rights =
model_identifier =
model_access_and_license =
project_description =
collection_methodology =
annotation_methodology =
quality_control_methodology =
image_folder =
model_weights =
default_class = __DEFAULT__
class_colours = #0f766e
snapping_tolerance_px = 5
snap_new_enabled = false
snap_edits_enabled = false
reverse_horizontal_wheel = false
simplify_vertex_distance_px = 7
simplify_vertex_count = 100
show_vertex_ids = true
show_labels = false
key_binding_undo = u
key_binding_new_annotation = n
key_binding_new_polygon = q
key_binding_new_rectangle = r
key_binding_delete_annotation = d
key_binding_merge_annotation = m
key_binding_simplify_polygon = s
key_binding_draw_arrow = a
key_binding_flag_review = f
key_binding_change_class = c
key_binding_delete_vertices = d
key_binding_cancel = c
prefs_version = 1.9.4
last_image_folder =
last_image_name =
last_image_index =
write_json_backups = true
crop_padding_px = 20
show_overlapping_edges = false
overlapping_edge_colour = #7c3aed
overlapping_edge_width = 3
live_lines = true
autoclose_enabled = false
snap_live_line_colour = #16a34a
key_binding_autoclose = w
selected_shared_edge_colour = #7dd3fc
key_binding_multi_select = x
